# Generated by Django 3.2.3 on 2023-05-12 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_actividad_asignacion_comentario_respuestaactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='social.actividad'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
